# _config.yml

url: "https://ipopop.github.io/Business-Site-in-Jekill-and-BootStrap-4" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Business-Site-in-Jekill-and-BootStrap-4" # the name of your site, e.g. ACME Corp.

sass:
  sass_dir: _sass
  style: compressed
